# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd0b3c66023388bbdc8bf4811a0a5efa2e115a9966c38b338878983de4982792094921672cf2e379d4d8d75ca502fdbad99fb4400e38c359f15bec26d7829963

test:
  secret_key_base: c211bca41b1e7f4d14fe7cb221ccd1931be296993afb468c64cbbff5d47e1ac08ca8fc3d6246f1c74f1a87d10b3338960fad37628e3011acf6c4175e8e03f764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
